relationship_id: REL-2022-0055
name: Application domain started
contributors:
- Jose Rodriguez @Cyb3rPandaH
- Roberto Rodriguez @Cyb3rWard0g
attack: null
behavior:
  source: application domain
  relationship: started
  target: null
security_events:
- event_id: 53504
  name: Windows PowerShell has started an IPC listening thread on a process in AppDomain.
  platform: windows
  channel: Microsoft-Windows-PowerShell/Operational
  log_source: Microsoft-Windows-PowerShell
  event_version:
  - '1'
references:
notes:
- Potential contribution for ATT&CK - Command / command context
