relationship_id: REL-2022-0086
name: Application attempted to authenticate User
contributors:
- Jose Rodriguez @Cyb3rPandaH
attack:
  data_source: User Account
  data_component: user account authentication
behavior:
  source: application
  relationship: attempted to authenticate
  target: user
security_events:
- event_id: ConsoleLogin
  name: ConsoleLogin
  platform: AWS
  audit_category: AwsConsoleSignin
  audit_sub_category: null
  log_channel: null
  log_provider: CloudTrail
  event_version: ['1.05']
references:
- https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-non-api-events.html
notes:
- Potential contribution for ATT&CK - User Account / user account authentication