relationship_id: REL-2022-0011
name: Application host started
contributors:
- Jose Rodriguez @Cyb3rPandaH
- Roberto Rodriguez @Cyb3rWard0g
attack:
behavior:
  source: application host
  relationship: started
  target: null
security_events:
- event_id: 400
  name: Engine state is changed from None to Available.
  platform: windows
  log_source: powershell
  event_version: ['0']
references:
notes:
- Potential contribution for ATT&CK - Command / command context