relationship_id: REL-2022-0127
name: Firewall attempted to load Configuration
contributors:
- Ruben Bouman @rubinatorz
attack:
  data_source: firewall
  data_component: firewall metadata
behavior:
  source: firewall
  relationship: attempted to load
  target: configuration
security_events:
- event_id: 2009
  name: The Windows Firewall service failed to load Group Policy.
  platform: windows
  channel: Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
  log_source: Microsoft-Windows-Windows Firewall With Advanced Security
  event_version: []
references: null
notes: null
