relationship_id: REL-2022-0016
name: User started Application host
contributors:
- Jose Rodriguez @Cyb3rPandaH
- Roberto Rodriguez @Cyb3rWard0g
attack: null
behavior:
  source: user
  relationship: started
  target: application host
security_events:
- event_id: '4103'
  name: Module logging.
  platform: windows
  channel: Microsoft-Windows-PowerShell/Operational
  log_source: Microsoft-Windows-PowerShell
  event_version:
  - '1'
references: null
notes:
- Potential contribution for ATT&CK - Command / command execution
