relationship_id: REL-2022-0106
name: User attempted to authenticate to Application
contributors:
- Jose Rodriguez @Cyb3rPandaH
attack:
  data_source: User Account
  data_component: user account authentication
behavior:
  source: user
  relationship: attempted to authenticate to
  target: application
security_events:
- event_id: cloudtrail
  name: cloudtrail
  platform: aws
  log_source: cloudtrail
  filter_in:
    - eventName: ConsoleLogin
    - eventType: AwsConsoleSignin
  event_version: ['1.05']
references:
