name: User started Application host
contributors:
- Jose Rodriguez @Cyb3rPandaH
- Roberto Rodriguez @Cyb3rWard0g
attack:
behavior:
  source: user
  relationship: started
  target: application host
security_events:
- event_id: 4103
  name: Module logging.
  platform: windows
  audit_category: Executing Pipeline
  log_channel: Microsoft-Windows-PowerShell/Operational
  log_provider: Microsoft-Windows-PowerShell
references:
notes:
- Potential contribution for ATT&CK - Command / command execution